### ISSUE TITLE
nuxt build stucks without exiting

### ISSUE THREAD

**Issue by lupus78** [arashsheyda/nuxt-mongoose#25] opened 2023-10-02 20:00 UTC
`npm run build` finishes, but the process is not terminated.

```
✔ You can preview this build using node .output/server/index.mjs 
```

If you end it with Ctrl-C, the build is fine and working.

After many tests I figured out it a combination of prerender and nuxt-mongoose.

nuxt.config.ts
```
export default defineNuxtConfig({
  modules: [
    'nuxt-mongoose',
  ],

  nitro: {
    prerender: {
      // routes: ['/']
    }
  },

  routeRules: {
    '/': { prerender: true },
  },

  mongoose: {
    uri: 'mongodb://localhost:27017/whatever'
  },

  devtools: { enabled: true }
})
```

In this configuration the build never exits.

If prerender is turned off (with either nitro.prerender.rules or routeRoules ) the build finishes and exits.
if the nuxt-mongoose module is disabled the build finishes and exits.

Someone has the same issue with details here: https://stackoverflow.com/questions/77027136/nuxts-npm-run-build-stuck-because-of-nuxt-mongoose

**Comment by arashsheyda** [comment] 2023-10-02 20:18
What version of nuxt and nuxt-mongoose are you using? In the last update this problem was solved

**Comment by lupus78** [comment] 2023-10-02 20:21
it's all the latest

```
------------------------------
- Operating System: Linux
- Node Version:     v18.17.1
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  npm@9.6.7
- Builder:          -
- User Config:      modules, nitro, routeRules, mongoose, devtools
- Runtime Modules:  nuxt-mongoose@1.0.1
- Build Modules:    -
------------------------------
```

**Comment by arashsheyda** [comment] 2023-10-03 00:39
interesting! the `mongoose connection` in `server/plugins` is causing this when prerender is enabled. I'll try to find a way to fix this. thanks for pointing this out.

**Comment by lupus78** [comment] 2023-10-03 07:07
just a tip. you might close the connection on a nitro hook:

https://nuxt.com/docs/api/advanced/hooks#nitro-app-hooks-runtime-server-side
https://nuxt.com/docs/guide/going-further/hooks#nitro-app-hooks-runtime

the `build:done` hook seems to be the place

**Comment by arashsheyda** [comment] 2023-10-04 01:49
yes it is fixed when closing it on close hook. thank you.

**Closed** 2023-10-04 01:56 UTC

**Comment by PrimeTimeTran** [comment] 2023-12-01 21:35
This continues to happen for me when I run with `1.0.3`. 

My build hangs in CI on this line.

`Σ Total size: 97.1 MB (21.7 MB gzip)`

Here's my config.

```
- Operating System: Darwin
- Node Version:     v18.18.2
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.4
- Builder:          -
- User Config:      ssr, devtools, devServer, plugins, css, nitro, ignore, formkit, runtimeConfig, typescript, modules, vuefire, mongoose, hooks, postcss, content, build
- Runtime Modules:  @nuxtjs/tailwindcss@6.10.1, @nuxt/content@2.9.0, nuxt-mongoose@1.0.3, @nuxtjs/color-mode@3.3.2, @formkit/nuxt@1.3.2, nuxt-vuefire@0.4.1
- Build Modules:    -
```



Here's nuxt.config.ts
```ts
mongoose: {
    uri: process.env.MONGODB_URI,
    options: {},
    modelsDir: 'models',
  },
  hooks: {
    'build:done': (go: HookResult) => {
      console.log({
        go,
      })
    },
  },
```

Setting MONGODB_URI seems to cause the issue for me.

I didn't have it set before, but when I deployed my app the db couldn't connect(whereas on my local it did.

Mind suggesting a solution? Thanks in advance

**Comment by arashsheyda** [comment] 2023-12-05 23:04
@PrimeTimeTran not sure why that happens, do you mind share a small reproduction? I've tested on several servers and it's working, also the `uri` is set to `process.env.MONGODB_URI` by default so there is no need to setting it in your `nuxt.config`

and,
you can use the `mongoose` instence from `import mongoose from 'mongoose'`

>     'build:done': (go: HookResult) => {
>       // Unsure of how to access the mongoose instance to exit here.
>       mongoose.disconnect()
>     },

**Comment by PrimeTimeTran** [comment] 2023-12-13 06:00
I'm not sure either. I blew away my lock files, node modules, dist, .nuxi, caches, etc and still got the behavior.

After troubleshooting with process of elimination I discovered the issue was it always hangs when I 
have the `process.env MONGODB_URI` set. 

I didn't realize it at first as I'm new to nuxt/ssr. I'd always just manually stop it and then run and see everything looked ok and move on with live. In CI/CD it'd always hang and fail my bid though. My solution has been since then to build locally(killing process after it hands) and then push to my hosting provider.

I'll try your solution though as it looks better.

Thanks in advance~!

**Comment by navkuun** [comment] 2024-02-28 20:41
I had the same issue, the following hook added to my nuxt.config.ts did the trick and it successfully deployed!

```
hooks: {
    close: (nuxt) => {
      if (!nuxt.options._prepare)
        process.exit()
    }
  }
  ```
